### ISSUE TITLE
Async events

### ISSUE THREAD

**Issue by mbosc** [wise0704/python-cs-events#4]
Man thanks for this library, it's really a small gem for C# aficionados working in python!

With the work I'm currently doing, however, I am working mostly with async functions. I ended up bootlegging the code of your _events.py and tweaking it to have an async AEvent class (i.e. you cannot simply call it but must await its __call__ method to trigger the attached events).

I can open a pull request if you like, but I haven't worked on any other part of your library (decorators and collections), so I wanted to check with you whether you're interested in it.

Thanks again!

**Comment by wise0704** [comment]
Sorry for getting to this late.

Could you show me a simple use case of such async events?
By default, it's not provided by C# (although it's pretty trivial to create an async delegate type for event handlers).
There are two approaches possible to achieve this. Looking into the usages might help me decide what's best.

<details>

The simplest way is to just add an async method `Event.invoke_async()` that calls synchronous callbacks normally and `create_task()` for async callbacks using `inspect.iscoroutinefunction()`.
In this case no other modifications need to be done to other classes, but it also means that there is no type checking for strictly async/sync callbacks only. Invoking the event normally will not call the async callbacks either.

Another approach is like you mentioned just adding another class `AsyncEvent`. It will be similar to C#'s approach of adding a new delegate type manually:

```c#
public delegate Task AsyncEventHandler(object sender, EventArgs e);
...
public event AsyncEventHandler ItemChanged;
```

Then the callbacks will be called via `gather()` or a for loop with a `TaskGroup`.
Additional respective classes for decorator and collections will need to be created.

</details>
